apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: resilient_pid
      defaultBucket: wireless_pid_metrics
    secureJsonData:
      token: testbed_secret_token_123